### ISSUE TITLE
Image white after scrolling "away"

### ISSUE THREAD

**Issue by mbpictures** [GregoryNative/react-native-gl-image-filters#27]
Hi!

I have a list (grid using this repo: https://github.com/saleel/react-native-super-grid) but after I scroll down, so the first row gets out of view, and then scroll back up, all images disappeared.

Do you have a solution to this problem?
Thanks already! :)

**Comment by GregoryNative** [comment]
Hello @mbpictures. Can you make a repo with example of this specific usage? I will take a look, but probably it's related to gl-react / gl-react-native itself.

**Comment by mbpictures** [comment]
Thanks for your reply, here's an example on [snack](https://snack.expo.io/!bGpQplj8).

**Comment by GregoryNative** [comment]
I've made a simple example on top of yours  and found that problem is still same even without `ImageFilters`. I've tried `LinearCopy`.

Also try this [snack](https://snack.expo.io/@gregoryrn/graceful-donuts). I can assume that problem is in react-native-super-grid library. In example I've tried `ScrollView` instead and it's working fine.

My solution for you is to use FlatList from react-native with [numcolumns](https://reactnative.dev/docs/flatlist#numcolumns) property instead.

Good luck @mbpictures.

**Comment by mbpictures** [comment]
Thanks for your answer!
I tried your snack and for me it's working fine with LinearCopy. I also tried the "normal" Image component whichs works pretty well. I also tried FlatList as you recommended, but there the issue remains the same :(

**Comment by GregoryNative** [comment]
Well, you can create issue in gl-react-expo as it's used as Surface for Expo. Hope they will help you 👍
